name: CMake on multiple platforms

on:
  push:
    branches: ["master"] # Trigger on push to master
  pull_request:
    branches: ["master"] # Trigger on pull requests to master

jobs:
  build_windows: # Fixed Windows configuration with Ninja and MSVC
    runs-on: windows-latest # Running on Windows runner
    # Example command: "C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\CommonExtensions\Microsoft\CMake\CMake\bin\cmake.exe" --build C:/Users/user/source/repos/Smart_Sliding_Gate/Build --config Debug --target IO_Test --
    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      - name: Set reusable strings # Set output variables for reuse
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: Configure CMake # Run CMake configuration step
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -G "Ninja"
          -DCMAKE_CXX_COMPILER=cl
          -DCMAKE_C_COMPILER=cl
          -DCMAKE_BUILD_TYPE=Debug
          -S ${{ github.workspace }}
      - name: Build # Build the IO_Test target in Debug mode
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug --target IO_Test

  build_ubuntu: # Fixed Ubuntu configuration with GCC
    runs-on: ubuntu-latest # Running on Ubuntu runner
    steps:
      - uses: actions/checkout@v4 # Checkout the repository
      - name: Set reusable strings # Set output variables for reuse
        id: strings
        shell: bash
        run: |
          echo "build-output-dir=${{ github.workspace }}/build" >> "$GITHUB_OUTPUT"
      - name: Configure CMake # Run CMake configuration step
        run: >
          cmake -B ${{ steps.strings.outputs.build-output-dir }}
          -G "Ninja"
          -DCMAKE_CXX_COMPILER=g++
          -DCMAKE_C_COMPILER=gcc
          -DCMAKE_BUILD_TYPE=Debug
          -S ${{ github.workspace }}
      - name: Build # Build the SlidingGate target in Debug mode
        run: cmake --build ${{ steps.strings.outputs.build-output-dir }} --config Debug --target SlidingGate
